### ISSUE TITLE
Add static website deployment \w ghPages

### ISSUE THREAD

**Issue by bzz** [bblfsh/uast-viewer#21]
It would be great to have documentation \w exampled available.
 
This issue scope is
 - have a static website with examples deployed using GH pages from this repo
 - add custom CNAME uast-viewer.bblfh.sh
 - update README.md to include links to it

Improvements of the static website style i.e to make it consistent with the rest of bblfsh docs, would be tracked under a separate issue.

**Comment by smacker** [comment]
@bzz 
1) somebody needs to set GITHUB_TOKEN to travis settings
2) should I create an issue for infra to point uast-viewer.bblfh.sh -> github?

**Comment by bzz** [comment]
Token added. 

Let's start with https://bblfsh.github.io/uast-viewer and I'll configure the GH pages to use custom domain, as soon as actual CNAME record is [added by Infra](https://github.com/src-d/issues-infrastructure/issues/183)

**Comment by bzz** [comment]
@smacker http://uast-viewer.bblf.sh 🎉 

Shall we update README and close this guy?
