### ISSUE TITLE
Update npm token in travis

### ISSUE THREAD

**Issue by smacker** [bblfsh/uast-viewer#42]
Publishing new versions don't work anymore.

Due to a recent security incident, all user tokens have been invalidated.
Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details.
To generate a new token, visit https://www.npmjs.com/settings/~/tokens

**Comment by bzz** [comment]
Thank you for the heads up!
A new token has been created and added to https://travis-ci.org/bblfsh/uast-viewer/settings
