### ISSUE TITLE
Make viewer data-schema agnostic by configuration

### ISSUE THREAD

**Issue by smacker** [bblfsh/uast-viewer#43]
What have been done:

1. Prior work allowed to redefine node schema in components:
https://github.com/bblfsh/uast-viewer/blob/master/src/components/Node.js#L167
example of the schema for protobuf:
https://github.com/smacker/dashboard/commit/ee85557216081c58e8de52b460f0c1687afdcaf2#diff-645b38198e35b22023728f730d1745efR12
2. The position index was also rewritten in a structure-agnostic way.

But the helpers:
- https://github.com/bblfsh/uast-viewer/blob/master/src/helpers.js#L86
- https://github.com/bblfsh/uast-viewer/blob/master/src/helpers.js#L108

still rely on `StartPosition` & `EndPosition` properties.

What is worse - those helpers are hard-coded in HoC: https://github.com/bblfsh/uast-viewer/blob/master/src/withUASTEditor.js#L39

**Comment by bzz** [comment]
added to the backlog
