### ISSUE TITLE
WithEditor HoC doesn't respect rootIds

### ISSUE THREAD

**Issue by smacker** [bblfsh/uast-viewer#44]
HoC keeps the state of nodes (collapsed, expanded, highlighted)
https://github.com/bblfsh/uast-viewer/blob/master/src/withUASTEditor.js#L18
But when new rootIds are passed the state stays unchanged.

Looks like in all use cases when rootIds are changed the state must be reset. Here is some work has been done: https://github.com/smacker/dashboard/blob/bblfsh_js/src/withUASTEditor.js#L99
But it requires more changes:
- current transformer must _only_ flatten tree and set a parent
- flatten tree should be partially expanded according to configuration & rootIds independently of user-provided transformer
- on rootIds change flatten tree should be reset to the initial state and re-expanded https://github.com/smacker/dashboard/blob/bblfsh_js/src/withUASTEditor.js#L117

**Comment by bzz** [comment]
Added to the backlog
