### ISSUE TITLE
Misleading uast prop in UASTViewer uncontrolled mode

### ISSUE THREAD

**Issue by carlosms** [bblfsh/uast-viewer#76]
The `uast` prop of `UASTViewer` behaves in an unexpected way. Changes to this `prop` do not change the UAST being rendered, it just sets the initial state.

This should be reflected in a different prop name, like `initialUAST`, and in the documentation:
- Prop description in https://uast-viewer.bblf.sh/#/UI%20Components?id=uastviewer
- A mention to this behaviour and how to force a new rendering in https://uast-viewer.bblf.sh/#/Use%20cases?id=uncontrolled

**Comment by smacker** [comment]
it also makes sense to add a warning in dev mode when both `uast` and `initialUAST` props are passed to mention that the latest is ignored.
